version: '3'
services:
    video-uploder-api:
      env_file:
        - ./video-uploader-api/.env
      build: ./video-uploader-api
      ports:
        - 8080:8080
      restart: on-failure
      depends_on:
        - postgres-db

    postgres-db:
      image: "postgres:9.6-alpine"
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
      restart: always
      environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      ports:
        - "5432:5432"
      volumes:
        - ./video-uploader-api/scripts:/docker-entrypoint-initdb.d/

    video-uploder-ui:
      env_file:
        - ./video-uploader-ui/.env
      build: ./video-uploader-ui
      ports:
        - 3000:3000
      restart: on-failure
      